# Generated by Django 3.0.2 on 2020-01-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='cloth.OrderedProduct'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
