# Generated by Django 3.0.2 on 2020-01-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0006_auto_20200121_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
